

GENOME_BUILD: GRCh38

SCORE_BINS:
    sum_spliceai_score_bins:
        - "0.0-0.01"
        - "0.01-0.05"
        - "0.05-0.1"
        - "0.1-0.25"
        - "0.25-0.5"
        - "0.5-1.0"
        - "1.0-1.75"
        - "1.75-4.0"

    max_spliceai_score_bins:
        - "0.0-0.1"
        - "0.1-0.2"
        - "0.2-0.4"
        - "0.4-0.6"
        - "0.6-0.8"
        - "0.8-1.0"

PAR:
    GRCh37:
        NOTE: "BUILD = GRCh37. The X chromosome Pseudoautosomal Regions (PAR). The start positions in this dict for each PAR is 0-based"
        X_PAR1:
            start: 60000
            end: 2699520
        X_PAR2:
            start: 154931043
            end: 155260560
        X_NONPAR:
            start: 2699520
            end: 154931043
    GRCh38:
        NOTE: "BUILD  = GRCh38. The X chromosome Pseudoautosomal Regions (PAR). The start positions in this dict for each PAR is 0-based"
        X_PAR1:
            start: 10000
            end: 2781479
        X_PAR2:
            start: 155701382
            end: 156030895
        X_NONPAR:
            start: 2781479
            end: 155701382


LOG_FILES:
    error_log: "ConSplice.ERROR"
    out_log: "ConSplice.OUT"
